// Catalog of UAE areas covered by news.investwithraj.com.
// Expanded in Wave 6 (Block 3.3) to ~30 priority areas across Dubai, Abu
// Dhabi, and Ras Al Khaimah. Each is a programmatic landing page at
// /areas/[slug] and surfaces on the homepage WorldMap.

import type { AreaPage } from "./types";

// Compact builder — every entry inherits sane defaults so the data block
// stays readable. Body is empty Day-1 (filled by programmatic-area job).
function area(input: {
  slug: string;
  name: string;
  emirate: AreaPage["emirate"];
  kind: AreaPage["kind"];
  oneLiner: string;
  excerpt: string;
  lat: number;
  lng: number;
  developers: string[];
  stats: AreaPage["stats"];
  medianAedPerSqft?: number;
  netYieldBand?: AreaPage["netYieldBand"];
  iwrNoteSlug?: string;
  iwrRootAreaSlug?: string;
}): AreaPage {
  const now = "2026-05-26T00:00:00Z";
  return {
    slug: input.slug,
    name: input.name,
    emirate: input.emirate,
    kind: input.kind,
    oneLiner: input.oneLiner,
    excerpt: input.excerpt,
    coords: { lat: input.lat, lng: input.lng },
    publishedAt: now,
    modifiedAt: now,
    body: "",
    stats: input.stats,
    developers: input.developers,
    medianAedPerSqft: input.medianAedPerSqft,
    netYieldBand: input.netYieldBand,
    faq: [],
    citations: [],
    heroImage: {
      src: `/areas/${input.slug}-placeholder.jpg`,
      alt: `${input.name}, ${input.emirate}`,
      credit: "Placeholder — sourced image to follow",
    },
    iwrNoteSlug: input.iwrNoteSlug,
    iwrRootAreaSlug: input.iwrRootAreaSlug,
  };
}

/** 27 additional priority areas (Hudayriyat / Palm Jebel Ali / Wynn already in index). */
export const ADDITIONAL_AREAS: AreaPage[] = [
  // ─── DUBAI (16) ─────────────────────────────────────────────────────
  area({
    slug: "downtown-dubai",
    name: "Downtown Dubai",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "The trophy core. Burj Khalifa, branded residences, AED 4,800+ psf at the top.",
    excerpt: "Downtown is the UAE's reference market — Burj Khalifa, Address Sky View, Armani Residences, IL Primo. Trophy pricing, low yield, but the comp every other Dubai market is measured against.",
    lat: 25.1972, lng: 55.2744,
    developers: ["Emaar Properties"],
    medianAedPerSqft: 2950,
    netYieldBand: { min: 4.5, max: 6.0 },
    stats: [
      { value: "AED 4,800+", unit: "psf", label: "Trophy branded residence top-tier" },
      { value: "AED 2,950", unit: "psf · median", label: "Mainstream apartment median" },
      { value: "Emaar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "dubai-marina",
    name: "Dubai Marina",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "The yield workhorse. ~7% net on right product, deepest secondary market in the UAE.",
    excerpt: "Dubai Marina is the most-traded community in the UAE — deepest secondary, fastest exit, the benchmark for tenant demand. Lower trophy ceiling than Palm or Downtown, but tighter yields and faster price discovery.",
    lat: 25.0805, lng: 55.1403,
    developers: ["Emaar Properties", "Damac", "Select Group"],
    medianAedPerSqft: 2200,
    netYieldBand: { min: 6.0, max: 7.5 },
    stats: [
      { value: "AED 2,200", unit: "psf · median", label: "Apartment secondary median" },
      { value: "6.0–7.5%", unit: "net yield", label: "Working band on rented stock" },
      { value: "120+", unit: "towers", label: "Density that makes the secondary deep" },
    ],
  }),
  area({
    slug: "palm-jumeirah",
    name: "Palm Jumeirah",
    emirate: "Dubai",
    kind: "island",
    oneLiner: "Original Palm. Mansion + branded-residence comp pool for the whole UAE.",
    excerpt: "Palm Jumeirah is the comp pool every Dubai luxury developer benchmarks against — Atlantis, One Palm, FIVE, Anantara, W. AED 8,000+ psf at the top of branded residence stack. The trophy that drove every imitator.",
    lat: 25.1124, lng: 55.1390,
    developers: ["Nakheel", "Omniyat", "Sobha"],
    medianAedPerSqft: 4200,
    iwrNoteSlug: "palm-jebel-ali-rerating",
    stats: [
      { value: "AED 8,000+", unit: "psf · trophy", label: "One Palm / Atlantis Royal Residences" },
      { value: "AED 4,200", unit: "psf · median", label: "Apartment secondary median" },
      { value: "16", unit: "fronds", label: "Original Palm geometry" },
    ],
  }),
  area({
    slug: "jbr",
    name: "Jumeirah Beach Residence",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "Beachfront yield play. The Walk anchored, holiday-let economics work here.",
    excerpt: "JBR is the original beachfront-apartment cluster — 40 towers, The Walk retail spine, direct beach access. Strong short-let economics for AirDXB / holiday-let operators. Older stock, but the beachfront is the moat.",
    lat: 25.0779, lng: 55.1334,
    developers: ["Dubai Properties"],
    medianAedPerSqft: 2050,
    netYieldBand: { min: 6.5, max: 8.5 },
    stats: [
      { value: "AED 2,050", unit: "psf · median", label: "Apartment secondary" },
      { value: "6.5–8.5%", unit: "net yield", label: "Long-let band — short-let higher" },
      { value: "40", unit: "towers", label: "Beachfront cluster scale" },
    ],
  }),
  area({
    slug: "business-bay",
    name: "Business Bay",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "The off-plan engine. Highest launch count + most live cranes anywhere in Dubai.",
    excerpt: "Business Bay is where most new Dubai stock is currently being built — Damac, Sobha, Select, Binghatti all running active off-plan there. Pre-handover discount → trade-up to Downtown story plays here.",
    lat: 25.1879, lng: 55.2632,
    developers: ["Damac", "Sobha Realty", "Select Group", "Binghatti"],
    medianAedPerSqft: 1900,
    netYieldBand: { min: 6.0, max: 7.5 },
    stats: [
      { value: "AED 1,900", unit: "psf · median", label: "Apartment secondary" },
      { value: "60+", unit: "active cranes", label: "Pipeline 2026 estimate" },
      { value: "30%+", unit: "off-plan share", label: "Of total Dubai launch volume" },
    ],
  }),
  area({
    slug: "jlt",
    name: "Jumeirah Lake Towers",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "The yield bunker. Tightest cap rates in Dubai, deepest tenant pool.",
    excerpt: "JLT is the highest-yielding apartment cluster in mainland Dubai — DMCC free-zone tenant base, 80 towers around the lake clusters, fastest tenant turnover in the UAE. Yields hold structurally because rents drive everything.",
    lat: 25.0699, lng: 55.1422,
    developers: ["DMCC", "Damac", "Almas"],
    medianAedPerSqft: 1500,
    netYieldBand: { min: 7.0, max: 9.0 },
    stats: [
      { value: "7.0–9.0%", unit: "net yield", label: "Among UAE's highest in apartments" },
      { value: "AED 1,500", unit: "psf · median", label: "Apartment secondary" },
      { value: "80", unit: "towers", label: "JLT cluster density" },
    ],
  }),
  area({
    slug: "difc",
    name: "Dubai International Financial Centre",
    emirate: "Dubai",
    kind: "free-zone",
    oneLiner: "The institutional address. UHNW corporate housing + Index Tower trophy.",
    excerpt: "DIFC is the address for institutional UHNW tenants — banks, hedge funds, family offices. Index Tower, Burj Daman, Gate Avenue. Smaller residential float than other clusters but the rents lead the city.",
    lat: 25.2138, lng: 55.2806,
    developers: ["DIFC Investments"],
    medianAedPerSqft: 2750,
    stats: [
      { value: "AED 2,750", unit: "psf · median", label: "Apartment secondary" },
      { value: "AED 300+", unit: "psf rent", label: "Top-of-stack annual rent" },
      { value: "44", unit: "residential", label: "Approx tower count in residential float" },
    ],
  }),
  area({
    slug: "dubai-hills-estate",
    name: "Dubai Hills Estate",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "Emaar's villa-led masterplan. Golf-anchored, family core, AED 1,500+ psf villa pricing.",
    excerpt: "Dubai Hills is Emaar's flagship villa-led community — golf course at the spine, Dubai Hills Mall, branded townhouses, mansions. The family-buyer benchmark for Dubai prime suburban.",
    lat: 25.1138, lng: 55.2403,
    developers: ["Emaar Properties"],
    medianAedPerSqft: 1850,
    netYieldBand: { min: 5.0, max: 6.5 },
    stats: [
      { value: "AED 1,850", unit: "psf · median", label: "Villa secondary" },
      { value: "18-hole", unit: "course", label: "Golf course anchored masterplan" },
      { value: "Emaar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "jvc",
    name: "Jumeirah Village Circle",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "The volume play. Highest off-plan transaction count in Dubai, AED 1,100 entry psf.",
    excerpt: "JVC is the most-transacted off-plan community in Dubai by count — affordable entry, broad developer mix (Binghatti, Samana, Tiger, Object 1), strong rental demand from young professionals. Volume drives liquidity.",
    lat: 25.0586, lng: 55.2074,
    developers: ["Binghatti", "Samana", "Tiger Group", "Object 1"],
    medianAedPerSqft: 1100,
    netYieldBand: { min: 7.0, max: 9.0 },
    stats: [
      { value: "AED 1,100", unit: "psf · median", label: "Apartment off-plan entry" },
      { value: "#1", unit: "off-plan count", label: "Most-transacted off-plan community" },
      { value: "7.0–9.0%", unit: "net yield", label: "Working band on rented stock" },
    ],
  }),
  area({
    slug: "damac-lagoons",
    name: "Damac Lagoons",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "Mediterranean-themed villa masterplan. Damac's flagship 2024-26 launch engine.",
    excerpt: "Damac Lagoons is Damac's villa-led answer to Dubai Hills — Mediterranean-themed clusters (Santorini, Costa Brava, Mykonos, Portofino), crystal lagoons throughout. Active hand-overs through 2027.",
    lat: 25.0250, lng: 55.2150,
    developers: ["Damac"],
    medianAedPerSqft: 1600,
    stats: [
      { value: "AED 1,600", unit: "psf · launch", label: "Villa launch median" },
      { value: "8", unit: "themed clusters", label: "Mediterranean concept set" },
      { value: "2027", unit: "completion", label: "Phase-1 final handover" },
    ],
  }),
  area({
    slug: "mbr-city",
    name: "Mohammed Bin Rashid City",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "Meydan-anchored. Crystal Lagoon, branded mansions, Meydan One the centerpiece.",
    excerpt: "MBR City is Dubai's largest masterplan by area — Meydan, District One, Sobha Hartland all sit inside it. Crystal Lagoon, mansion plots, branded villa stacks. The new luxury suburban core.",
    lat: 25.1659, lng: 55.3066,
    developers: ["Meydan", "Sobha", "Nakheel"],
    medianAedPerSqft: 2400,
    stats: [
      { value: "AED 2,400", unit: "psf · median", label: "Villa + apartment blended median" },
      { value: "7km²", unit: "Crystal Lagoon", label: "Largest man-made lagoon in the world" },
      { value: "District One", unit: "anchor", label: "Mansion-tier sub-community" },
    ],
  }),
  area({
    slug: "al-furjan",
    name: "Al Furjan",
    emirate: "Dubai",
    kind: "community",
    oneLiner: "Nakheel townhouse + apartment community. Affordable, metro-connected, family-priced.",
    excerpt: "Al Furjan is Nakheel's residential community west of Jumeirah — Discovery Gardens neighbor, Route 2020 metro line connection, mix of townhouses and apartments. The Dubai middle-class family default.",
    lat: 25.0263, lng: 55.1469,
    developers: ["Nakheel", "Azizi", "Danube"],
    medianAedPerSqft: 1250,
    netYieldBand: { min: 6.5, max: 8.0 },
    stats: [
      { value: "AED 1,250", unit: "psf · median", label: "Townhouse + apartment blended" },
      { value: "Route 2020", unit: "metro", label: "Direct metro line connection" },
      { value: "Nakheel", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "sobha-hartland",
    name: "Sobha Hartland",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "Sobha's flagship waterfront masterplan. AED 2,500+ psf, Hartland II + III in pipeline.",
    excerpt: "Sobha Hartland is Sobha Realty's flagship MBR City masterplan — green spaces, Hartland International School, dense apartment + villa mix, Hartland II + Hartland Estates in active launch.",
    lat: 25.1799, lng: 55.3140,
    developers: ["Sobha Realty"],
    medianAedPerSqft: 2500,
    stats: [
      { value: "AED 2,500", unit: "psf · median", label: "Apartment median" },
      { value: "8M sqft", unit: "GFA", label: "Hartland I + II + III combined" },
      { value: "Sobha", unit: "sole dev", label: "Single-developer masterplan" },
    ],
  }),
  area({
    slug: "dubai-creek-harbour",
    name: "Dubai Creek Harbour",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "Emaar's next-generation Downtown. Creek Tower planned, Dubai Square anchor.",
    excerpt: "Dubai Creek Harbour is Emaar's positioning for the next decade — Dubai Creek Tower (originally taller than Burj Khalifa, paused & resumed), Dubai Square mall, branded waterfront stack. Long-cycle play.",
    lat: 25.1948, lng: 55.3479,
    developers: ["Emaar Properties"],
    medianAedPerSqft: 1900,
    stats: [
      { value: "AED 1,900", unit: "psf · median", label: "Apartment launch median" },
      { value: "Dubai Creek Tower", unit: "icon", label: "Resumed development 2024+" },
      { value: "Emaar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "mina-rashid",
    name: "Mina Rashid",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "The Queen Elizabeth 2 anchor. Emaar's port-to-residence conversion masterplan.",
    excerpt: "Mina Rashid is Emaar's reactivation of the old Dubai port — QE2 docked permanently, Rashid Yachts & Marina, mid-rise residential stack, walkable waterfront. Distinct from Dubai Marina aesthetic.",
    lat: 25.2548, lng: 55.2723,
    developers: ["Emaar Properties"],
    medianAedPerSqft: 2100,
    stats: [
      { value: "AED 2,100", unit: "psf · launch", label: "Apartment launch median" },
      { value: "QE2", unit: "anchor", label: "Permanent docked icon" },
      { value: "Emaar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "tilal-al-ghaf",
    name: "Tilal Al Ghaf",
    emirate: "Dubai",
    kind: "master-plan",
    oneLiner: "Majid Al Futtaim's villa community. Crystal Lagoon, Serenity mansions tier on top.",
    excerpt: "Tilal Al Ghaf is Majid Al Futtaim's villa-led masterplan — Crystal Lagoon at the spine, Serenity mansions at the trophy end, Aura Gardens and Harmony for family. The MAF answer to Dubai Hills.",
    lat: 25.0322, lng: 55.2750,
    developers: ["Majid Al Futtaim"],
    medianAedPerSqft: 2200,
    stats: [
      { value: "AED 2,200", unit: "psf · median", label: "Villa median" },
      { value: "Crystal Lagoon", unit: "spine", label: "0.7km man-made lagoon" },
      { value: "Serenity", unit: "trophy", label: "Mansion sub-community top tier" },
    ],
  }),

  // ─── ABU DHABI (7 — Hudayriyat already in index) ────────────────────
  area({
    slug: "saadiyat-island",
    name: "Saadiyat Island",
    emirate: "Abu Dhabi",
    kind: "island",
    oneLiner: "The cultural island. Louvre, Guggenheim AD, Zayed National Museum. Mansion-tier villas.",
    excerpt: "Saadiyat is Abu Dhabi's cultural-anchor island — Louvre Abu Dhabi, Guggenheim (under construction), Zayed National Museum (under construction). Mansion-tier villa stack: Saadiyat Reserve, Mamsha Saadiyat, Soho Square.",
    lat: 24.5430, lng: 54.4180,
    developers: ["Aldar Properties", "TDIC"],
    medianAedPerSqft: 2400,
    stats: [
      { value: "AED 2,400", unit: "psf · median", label: "Villa + apartment blended median" },
      { value: "3", unit: "anchor museums", label: "Louvre + Guggenheim + Zayed National" },
      { value: "Aldar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "yas-island",
    name: "Yas Island",
    emirate: "Abu Dhabi",
    kind: "island",
    oneLiner: "Entertainment island. F1 circuit, Yas Marina, Ferrari World, Warner Bros, SeaWorld.",
    excerpt: "Yas is Abu Dhabi's entertainment island — F1 night race, Yas Marina, Ferrari World, Warner Bros, SeaWorld AD. Strong short-let economics, branded villa stack at Yas Bay + Yas Acres.",
    lat: 24.4859, lng: 54.6033,
    developers: ["Aldar Properties"],
    medianAedPerSqft: 1850,
    netYieldBand: { min: 6.0, max: 8.0 },
    stats: [
      { value: "AED 1,850", unit: "psf · median", label: "Apartment + villa blended" },
      { value: "F1", unit: "anchor", label: "Yas Marina Circuit annual race" },
      { value: "Aldar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "al-reem-island",
    name: "Al Reem Island",
    emirate: "Abu Dhabi",
    kind: "island",
    oneLiner: "Abu Dhabi's apartment yield core. ADGM-adjacent, deepest secondary in AD.",
    excerpt: "Al Reem is Abu Dhabi's most-transacted apartment cluster — Sun & Sky Towers, Marina Square, Reem Mall. ADGM proximity drives tenant demand. The AD answer to Dubai Marina.",
    lat: 24.4992, lng: 54.4054,
    developers: ["Aldar Properties", "Bloom", "Tamouh"],
    medianAedPerSqft: 1450,
    netYieldBand: { min: 6.5, max: 8.5 },
    stats: [
      { value: "AED 1,450", unit: "psf · median", label: "Apartment secondary" },
      { value: "6.5–8.5%", unit: "net yield", label: "Among AD's highest in apartments" },
      { value: "ADGM", unit: "adjacency", label: "Drives tenant base" },
    ],
  }),
  area({
    slug: "al-maryah-island",
    name: "Al Maryah Island",
    emirate: "Abu Dhabi",
    kind: "free-zone",
    oneLiner: "ADGM home + Cleveland Clinic. AD's DIFC equivalent. Trophy waterfront.",
    excerpt: "Al Maryah is Abu Dhabi's DIFC — ADGM free zone, Cleveland Clinic, The Galleria mall, Four Seasons + Rosewood. UHNW corporate housing + branded residences. Mini-island, max prestige.",
    lat: 24.5008, lng: 54.3839,
    developers: ["Mubadala", "Aldar"],
    medianAedPerSqft: 2500,
    stats: [
      { value: "AED 2,500", unit: "psf · median", label: "Branded residence + apartment" },
      { value: "ADGM", unit: "anchor", label: "Abu Dhabi Global Market financial centre" },
      { value: "Cleveland", unit: "clinic", label: "Hospital + medical-tourism anchor" },
    ],
  }),
  area({
    slug: "al-raha-beach",
    name: "Al Raha Beach",
    emirate: "Abu Dhabi",
    kind: "community",
    oneLiner: "Aldar's coastal masterplan. Al Bandar, Al Muneera, Al Zeina waterfront stack.",
    excerpt: "Al Raha Beach is Aldar's coastal residential strip on the AD-Dubai highway — Al Bandar, Al Muneera, Al Zeina sub-communities. Mid-rise apartments + townhouses, beach + marina access.",
    lat: 24.4291, lng: 54.5070,
    developers: ["Aldar Properties"],
    medianAedPerSqft: 1700,
    stats: [
      { value: "AED 1,700", unit: "psf · median", label: "Apartment + townhouse" },
      { value: "5km", unit: "coastline", label: "Beachfront stretch" },
      { value: "Aldar", unit: "primary", label: "Anchor developer" },
    ],
  }),
  area({
    slug: "masdar-city",
    name: "Masdar City",
    emirate: "Abu Dhabi",
    kind: "master-plan",
    oneLiner: "Sustainability-anchored. IRENA HQ, EV-only roads, Mubadala-developed.",
    excerpt: "Masdar City is Abu Dhabi's sustainability district — IRENA HQ, Khalifa University, EV-only inner roads, the Sustainability Pavilion (Expo 2020 legacy). Mubadala-developed, mid-rise mix.",
    lat: 24.4307, lng: 54.6178,
    developers: ["Mubadala"],
    medianAedPerSqft: 1550,
    stats: [
      { value: "AED 1,550", unit: "psf · median", label: "Apartment median" },
      { value: "IRENA", unit: "HQ", label: "International Renewable Energy Agency" },
      { value: "EV-only", unit: "inner roads", label: "Sustainability district mandate" },
    ],
  }),
  area({
    slug: "al-reef",
    name: "Al Reef",
    emirate: "Abu Dhabi",
    kind: "community",
    oneLiner: "Affordable villa community near AUH airport. Family-buyer entry point.",
    excerpt: "Al Reef is Abu Dhabi's most affordable villa community — Arabian, Mediterranean, Contemporary, Desert sub-villages. AUH airport proximity drives commuter base. Entry-level UAE family villa.",
    lat: 24.4495, lng: 54.6049,
    developers: ["Manazel"],
    medianAedPerSqft: 950,
    netYieldBand: { min: 6.5, max: 8.0 },
    stats: [
      { value: "AED 950", unit: "psf · median", label: "Villa secondary median" },
      { value: "4", unit: "village types", label: "Themed sub-community mix" },
      { value: "AUH airport", unit: "10min", label: "Commuter proximity" },
    ],
  }),

  // ─── RAS AL KHAIMAH (3 — Wynn Al Marjan already in index) ──────────
  area({
    slug: "al-marjan-island",
    name: "Al Marjan Island",
    emirate: "Ras Al Khaimah",
    kind: "island",
    oneLiner: "Wynn-anchored island. 4 coral-shaped sub-islands. Integrated-resort licence catalyst.",
    excerpt: "Al Marjan is Ras Al Khaimah's flagship master-plan island — Wynn Resort opening 2027 on Al Marjan 1, Rixos, Anantara, Hampton, Marjan Bay. The integrated-resort catalyst is the rerating thesis.",
    lat: 25.6891, lng: 55.7861,
    developers: ["Marjan", "RAK Properties"],
    medianAedPerSqft: 1500,
    iwrNoteSlug: "wynn-al-marjan-yield",
    stats: [
      { value: "AED 1,500", unit: "psf · median", label: "Branded residence median" },
      { value: "4", unit: "sub-islands", label: "Coral-shaped masterplan" },
      { value: "2027", unit: "Wynn open", label: "Integrated-resort catalyst date" },
    ],
  }),
  area({
    slug: "mina-al-arab",
    name: "Mina Al Arab",
    emirate: "Ras Al Khaimah",
    kind: "master-plan",
    oneLiner: "RAK Properties' coastal masterplan. InterContinental anchor, villa + apartment stack.",
    excerpt: "Mina Al Arab is RAK Properties' flagship coastal masterplan — InterContinental Mina Al Arab, Bermuda + Hayat Island sub-communities, Anantara at the trophy end. Quieter alternative to Marjan.",
    lat: 25.7178, lng: 55.8136,
    developers: ["RAK Properties"],
    medianAedPerSqft: 1100,
    stats: [
      { value: "AED 1,100", unit: "psf · median", label: "Villa + apartment blended" },
      { value: "InterContinental", unit: "anchor", label: "5-star branded hotel" },
      { value: "RAK Properties", unit: "sole dev", label: "Single-developer masterplan" },
    ],
  }),
  area({
    slug: "al-hamra-village",
    name: "Al Hamra Village",
    emirate: "Ras Al Khaimah",
    kind: "master-plan",
    oneLiner: "Al Hamra Real Estate's anchor masterplan. Waldorf, golf course, mansion + villa core.",
    excerpt: "Al Hamra Village is RAK's most-established master community — Waldorf Astoria, 18-hole golf course, Al Hamra Mall, marina. The mature RAK lifestyle anchor pre-dating the Wynn catalyst.",
    lat: 25.6970, lng: 55.7790,
    developers: ["Al Hamra Real Estate"],
    medianAedPerSqft: 1000,
    netYieldBand: { min: 6.0, max: 7.5 },
    stats: [
      { value: "AED 1,000", unit: "psf · median", label: "Villa secondary median" },
      { value: "Waldorf", unit: "anchor", label: "5-star branded hotel + spa" },
      { value: "18-hole", unit: "golf", label: "Course anchored masterplan" },
    ],
  }),
];
