// Auto-generated by the editorial publication pipeline (Block 15). Every
// material figure passed the source-bound evidence contract before publish.
// Do not hand-edit; re-run through the review pipeline.

import type { NewsArticle } from "./types";

export const article: NewsArticle = {
  "author": "raj-tomar",
  "body": "Hussein Ezz Eddin, the Chief Sales Officer of Prestige One Developments, said the developer plans to invest AED3 billion to AED4 billion during the 2026-2027 property season, WAM reports.\n\nPrestige One Developments intends to put the investment towards land purchases and new residential and commercial projects in Dubai. Prestige One Developments plans projects in key locations across Dubai.\n\nPrestige One Developments also plans a further seven to eight project launches during the current season, according to the executive's comments reported by WAM.",
  "category": "developer-corporate",
  "citations": [
    {
      "accessedAt": "2026-09-10T18:10:03.000Z",
      "source": "WAM (Emirates News Agency)",
      "tier": "government",
      "url": "https://www.wam.ae/en/article/c256iib-dubai-developers-launch-multi-billion-dirham"
    }
  ],
  "cta": {
    "href": "https://www.investwithraj.com/engage?utm_source=news&utm_medium=internal&utm_campaign=prestige_one_investment",
    "label": "Discuss your Dubai real estate decision with Raj"
  },
  "displayDate": "10 Sept 2026",
  "distribution": {},
  "faq": [],
  "format": "short-update",
  "heroImage": {
    "alt": "Dubai skyline at sunset, shown as city context",
    "credit": "Invest With Raj stock-account archive; Dubai city context, not a Prestige One project",
    "src": "/news/2026-09-10-prestige-one-dubai-investment-plan/cover.jpg",
    "sourceUrl": "https://www.investwithraj.com/media/licensed-real/dubai-golden.jpg",
    "rightsStatus": "licensed",
    "width": 7728,
    "height": 5152,
    "approval": "approved-editorial"
  },
  "market": [
    "Dubai"
  ],
  "metaDescription": "Prestige One's Dubai plans cover land acquisitions and new residential and commercial projects, WAM reports.",
  "modifiedAt": "2026-09-10T18:10:03.000Z",
  "publishedAt": "2026-09-10T18:10:03.000Z",
  "reportingBasis": {
    "organization": "Prestige One Developments",
    "sourceUrl": "https://www.wam.ae/en/article/c256iib-dubai-developers-launch-multi-billion-dirham",
    "speaker": "Hussein Ezz Eddin",
    "statementKind": "corporate-intent"
  },
  "slug": "2026-09-10-prestige-one-dubai-investment-plan",
  "speakableSelector": [
    ".article-body > p:first-child"
  ],
  "subtitle": "Prestige One's plans cover land purchases and new residential and commercial projects",
  "tier": "news",
  "title": "Prestige One plans to invest AED3 billion to AED4 billion",
  "tldr": [
    "Prestige One plans AED3 billion to AED4 billion of investment.",
    "Prestige One's plans cover land, residential and commercial projects.",
    "Prestige One plans seven to eight further launches this season."
  ],
  "publicationContentHash": "d4f4b354f1ae9c7692faf6ffe50d42e78da9cc1cda99c0636603b049ce202e8c",
  "status": "live"
};
