// Auto-generated by the editorial publication pipeline (Block 15). Every
// material figure passed the source-bound evidence contract before publish.
// Do not hand-edit; re-run through the review pipeline.

import type { NewsArticle } from "./types";

export const article: NewsArticle = {
  "author": "raj-tomar",
  "body": "Meraas, part of Dubai Holding Real Estate, awarded GCC Contracting a contract to construct 272 villas and town houses at Nad Al Sheba Gardens, The National reported on 24 September 2026.\n\nThe National reported that the development includes 130 villas with four to seven bedrooms and 142 three-bedroom town houses, alongside pool houses, utilities and infrastructure works. The National reported that construction has begun and completion is expected by June 2028.\n\nKhalid Al Malik, chief executive of Dubai Holding Real Estate, said the Phase 7 contract for Nad Al Sheba Gardens reflects continued demand for premium master-planned residential communities in Dubai, The National reported. The National reported that Al Malik said Meraas remains committed to delivering homes that combine architecture, connectivity and enduring value for residents and investors.\n\nThe National reported that Nad Al Sheba Gardens is about 10 minutes away from Downtown Dubai and has access links to Meydan racetrack and Dubai International Airport.",
  "category": "market-pulse",
  "citations": [
    {
      "accessedAt": "2026-09-25T20:28:04.076Z",
      "source": "The National",
      "tier": "national-press",
      "url": "https://www.thenationalnews.com/news/uae/2026/09/24/seven-bedroom-villas-to-be-built-in-dubais-nad-al-sheba-under-d1-billion-luxury-living-master-plan/"
    }
  ],
  "cta": {
    "href": "https://investwithraj.com/engage?utm_source=news&utm_medium=internal&utm_campaign=news_auto_draft&utm_content=newsletter-cta",
    "label": "Get the institutional read — work with Raj"
  },
  "displayDate": "26 Sept 2026",
  "distribution": {},
  "faq": [],
  "format": "short-update",
  "heroImage": {
    "alt": "Dubai skyline at sunset, shown as city context",
    "credit": "Invest With Raj stock-account archive; Dubai city context, not the announced project",
    "height": 5152,
    "rightsStatus": "licensed",
    "sourceUrl": "https://www.investwithraj.com/media/licensed-real/dubai-golden.jpg",
    "src": "/news/2026-09-26-meraas-awards-contract-to-gcc-contracting-for-272-villas-at/cover.jpg",
    "width": 7728,
    "approval": "approved-editorial"
  },
  "market": [
    "Dubai"
  ],
  "modifiedAt": "2026-09-25T20:28:04.076Z",
  "publishedAt": "2026-09-25T20:28:04.076Z",
  "slug": "2026-09-26-meraas-awards-contract-to-gcc-contracting-for-272-villas-at",
  "speakableSelector": [
    ".article-body > p:first-child"
  ],
  "subtitle": "Development includes 130 villas and 142 three-bedroom town houses",
  "tier": "news",
  "title": "Meraas awards contract to GCC Contracting for 272 villas at Nad Al Sheba Gardens",
  "tldr": [
    "Meraas awarded GCC Contracting a contract to construct 272 villas and town houses at Nad Al Sheba Gardens, The National reported.",
    "The National reported that the development includes 130 villas with four to seven bedrooms and 142 three-bedroom town houses, plus pool houses and infrastructure.",
    "The National reported that construction has begun and completion is expected by June 2028."
  ],
  "publicationContentHash": "a275e02044bf98361a3219be5c3279ea00c15385a847a2a4ee5682de0bf4f230",
  "status": "live"
};
