// v14 Draftly frame manifests — typed registry for all FrameScroll sections.
// Generated by scripts/generate-frames.mjs (Stage 2 of /draftly-up).
//
// Add a new section: append to MANIFESTS, run `npm run frames:generate`.

import type { FrameManifest } from "@/components/FrameScroll";

export const MANIFESTS = {
  hero: {
    frames: 160,
    desktopPath: "/draftly-frames/hero/desktop/",
    mobilePath: "/draftly-frames/hero/mobile/",
    ext: "webp",
    aspect: 16 / 9,
  },
  operator: {
    frames: 240,
    desktopPath: "/draftly-frames/operator/desktop/",
    mobilePath: "/draftly-frames/operator/mobile/",
    ext: "webp",
    aspect: 16 / 9,
  },
  market: {
    frames: 240,
    desktopPath: "/draftly-frames/market/desktop/",
    mobilePath: "/draftly-frames/market/mobile/",
    ext: "webp",
    aspect: 16 / 9,
  },
} satisfies Record<string, FrameManifest>;

export type ManifestKey = keyof typeof MANIFESTS;
