// Turn a reviewed draft article into a build-safe content/news/<slug>.ts module
// + the patched content/news/index.ts that registers it.
//
// The generated article file inlines everything (no rootCtaUrl import — the
// draft's cta.href is already a resolved string), injects status:"live", and
// emits a JSON object literal (valid TS — quoted keys + escaped strings are
// legal). This is a clean APPEND, never an in-place edit of an existing body.

import type { DraftArticle } from "./types";

/** Deterministic, collision-free, valid JS identifier from a slug. */
export function slugToVarName(slug: string): string {
  return "art_" + slug.replace(/[^a-zA-Z0-9]/g, "_");
}

/** The full content/news/<slug>.ts file content. */
export function serializeArticle(article: DraftArticle): string {
  const published: Record<string, unknown> = { status: "live", ...article };
  const literal = JSON.stringify(published, null, 2);
  return (
    `// Auto-generated by the editorial review pipeline (Block 15). Reviewed\n` +
    `// + approved by Raj before publish — every figure verified against a\n` +
    `// cited source. Do not hand-edit; re-run through the review cockpit.\n\n` +
    `import type { NewsArticle } from "./types";\n\n` +
    `export const article: NewsArticle = ${literal};\n`
  );
}

/** Insert the new article's import + registry entry into index.ts source.
 *  Idempotent-ish: if the slug already appears, returns the source unchanged. */
export function patchIndex(src: string, slug: string): string {
  const varName = slugToVarName(slug);
  if (src.includes(`from "./${slug}"`)) return src;

  const importLine = `import { article as ${varName} } from "./${slug}";`;

  // Insert the import after the last existing article import.
  const importMatches = [
    ...src.matchAll(/import \{ article as \w+ \} from "\.\/[^"]+";/g),
  ];
  let out = src;
  if (importMatches.length > 0) {
    const last = importMatches[importMatches.length - 1];
    const at = (last.index ?? 0) + last[0].length;
    out = out.slice(0, at) + "\n" + importLine + out.slice(at);
  } else {
    // Fallback: drop it just before the NEWS_ARTICLES declaration.
    out = out.replace(
      /(export const NEWS_ARTICLES)/,
      `${importLine}\n\n$1`,
    );
  }

  // Register the var at the top of the NEWS_ARTICLES array (newest first).
  out = out.replace(
    /(export const NEWS_ARTICLES:\s*NewsArticle\[\]\s*=\s*\[)/,
    `$1\n  ${varName},`,
  );

  return out;
}
