// Approval Queue — outreach drafts that need Raj's eyeball before posting.
//
// Pattern: the news pipeline auto-generates copy for channels that REQUIRE
// human judgment (Reddit, Quora, HARO/Qwoted, Stack Exchange, niche forums,
// Discord investor servers). Raj approves/skips/edits in a basic-auth-gated
// dashboard. Stale items auto-expire per channel SLA.
//
// Channels distinct from /lib/distribute (which is fully automated):
//   - distribute = own megaphones (LinkedIn, X, Telegram, Discord, IG, YT)
//   - queue      = third-party communities + media pitches

export type QueueChannel =
  | "reddit"            // r/dubai, r/dubairealestate, r/uaeinvesting, r/Realestateinvesting
  | "quora"             // Dubai real estate, UAE investing, Hudayriyat/Marjan questions
  | "haro"              // HARO journalist queries (response window 24h)
  | "qwoted"            // Qwoted source pitches
  | "featured"          // Featured.com expert responses
  | "stackexchange"     // Money.SE, Personal Finance.SE
  | "biggerpockets"     // BiggerPockets.com forum
  | "propertyhub"       // PropertyHub UK forum (UAE expat investors)
  | "discord-investor"  // niche Discord investor servers
  | "linkedin-comment"  // strategic comments on UHNW LinkedIn posts
  | "twitter-reply"     // strategic replies on real-estate Twitter
  | "telegram-group";   // Dubai investor Telegram groups

export type QueueStatus =
  | "pending"     // freshly generated, awaiting approval
  | "approved"    // Raj clicked APPROVE — ready to post (or copied to clipboard for manual post)
  | "posted"      // marked as posted (Raj clicked or external webhook confirmed)
  | "skipped"     // Raj said no
  | "expired"     // SLA timed out
  | "edited";     // Raj edited but hasn't approved yet — still pending review

export type QueueAction =
  | "approve"     // → posted (auto-post) or → approved (manual copy)
  | "skip"        // → skipped
  | "edit"        // change draftText, → edited
  | "postpone"    // bump expiresAt by 24h
  | "mark-posted" // for manual channels — Raj posts elsewhere then clicks done
  | "delete";     // remove from queue entirely

/** A single outreach draft waiting for review. */
export interface QueueItem {
  /** UUID — generated by storage layer */
  id: string;
  /** Which platform / surface */
  channel: QueueChannel;
  /** Where on the platform: subreddit name, question URL, HARO query ID, etc. */
  target: string;
  /** Draft text ready to copy/paste or auto-post */
  draftText: string;
  /** Why the pipeline thinks this is worth doing (1-2 sentence rationale) */
  rationale: string;
  /** Optional — link to the source news article that triggered this draft */
  sourceArticleSlug?: string;
  /** Optional — external URL the draft is responding to (Reddit post, Quora question, HARO query, etc.) */
  responseToUrl?: string;
  /** Current state */
  status: QueueStatus;
  /** ISO timestamp — when pipeline added it */
  createdAt: string;
  /** ISO timestamp — when it goes stale (per-channel SLA) */
  expiresAt: string;
  /** ISO timestamp — when Raj acted on it */
  actedAt?: string;
  /** ISO timestamp — when it actually got posted */
  postedAt?: string;
  /** URL of the resulting post (if known) — for tracking conversions later */
  postedUrl?: string;
  /** Free-form note Raj can leave when editing */
  editNote?: string;
  /** Conversion outcome — set later when we know if it drove leads */
  outcome?: "lead" | "engagement" | "ignored" | "removed-by-mod";
}

/** Channel-specific posting policy. */
export interface ChannelPolicy {
  /** Human-readable label for the dashboard */
  label: string;
  /** SLA for auto-expiry in hours */
  expiryHours: number;
  /** Whether posting can be automated (with API/OAuth wired up) */
  autoPostable: boolean;
  /** TOS / self-promo rule notes — surfaced in the dashboard */
  policyNote: string;
  /** Suggested approval cadence — "review-each" or "bulk-ok" */
  reviewMode: "review-each" | "bulk-ok";
}

export const CHANNEL_POLICIES: Record<QueueChannel, ChannelPolicy> = {
  reddit: {
    label: "Reddit",
    expiryHours: 24,
    autoPostable: false, // Reddit OAuth not wired yet — copy/paste for now
    policyNote:
      "Reddit 1-in-10 rule: ≤10% of your posts can be self-promo. Lead with value, link buried in context.",
    reviewMode: "review-each",
  },
  quora: {
    label: "Quora",
    expiryHours: 72,
    autoPostable: false,
    policyNote: "Answers > 300 words rank better. Lead with TL;DR, link in final paragraph only.",
    reviewMode: "review-each",
  },
  haro: {
    label: "HARO",
    expiryHours: 24,
    autoPostable: false,
    policyNote: "Journalist response window typically 24h. Quote-first, ≤200 words, include 1-line bio + headshot.",
    reviewMode: "review-each",
  },
  qwoted: {
    label: "Qwoted",
    expiryHours: 48,
    autoPostable: false,
    policyNote: "Similar to HARO but slower SLA. Same quote-first format.",
    reviewMode: "review-each",
  },
  featured: {
    label: "Featured.com",
    expiryHours: 72,
    autoPostable: false,
    policyNote: "Expert quote DB. 100-300 words, attributed quote-style.",
    reviewMode: "review-each",
  },
  stackexchange: {
    label: "Stack Exchange",
    expiryHours: 96,
    autoPostable: false,
    policyNote: "Money.SE + Personal Finance.SE. No self-promo links in answers — only in bio.",
    reviewMode: "review-each",
  },
  biggerpockets: {
    label: "BiggerPockets",
    expiryHours: 48,
    autoPostable: false,
    policyNote: "US-centric audience curious about Dubai. Educational framing only, no listings.",
    reviewMode: "review-each",
  },
  propertyhub: {
    label: "PropertyHub UK",
    expiryHours: 48,
    autoPostable: false,
    policyNote: "UK expat investor forum. UAE tax-resident angle resonates.",
    reviewMode: "review-each",
  },
  "discord-investor": {
    label: "Discord (Investor)",
    expiryHours: 48,
    autoPostable: false,
    policyNote: "Per-server rules vary wildly. Always check pinned channel rules first.",
    reviewMode: "review-each",
  },
  "linkedin-comment": {
    label: "LinkedIn Comment",
    expiryHours: 24,
    autoPostable: false,
    policyNote: "Comment on UHNW thought-leader posts. Add insight, never plug.",
    reviewMode: "review-each",
  },
  "twitter-reply": {
    label: "X / Twitter Reply",
    expiryHours: 12,
    autoPostable: false,
    policyNote: "Short and sharp. 1-2 sentences max. Reply within 1hr of original post.",
    reviewMode: "bulk-ok",
  },
  "telegram-group": {
    label: "Telegram Group",
    expiryHours: 24,
    autoPostable: false,
    policyNote: "Per-group admin rules. Lead with the data point, not the brand.",
    reviewMode: "review-each",
  },
};

/** Returns expiresAt timestamp for a channel, N hours from now. */
export function calculateExpiresAt(channel: QueueChannel, fromDate = new Date()): string {
  const policy = CHANNEL_POLICIES[channel];
  const expires = new Date(fromDate.getTime() + policy.expiryHours * 60 * 60 * 1000);
  return expires.toISOString();
}
