import assert from "node:assert/strict";
import {readFileSync} from "node:fs";
import {INSIGHT_ARTICLES, getInsightBySlug} from "../content/insights";
import {NEWS_ARTICLES} from "../content/news";
import {VERTICALS, articleMatchesVertical} from "../lib/verticals";
import {NEWS_ARCHIVE_DESKS} from "../lib/news-archive-projection";
import sitemap from "../app/sitemap";
const edition=getInsightBySlug("waterfront-beyond-the-view")!;
assert(edition && edition.body.split(/\s+/).length>650);
assert.equal(new Set(INSIGHT_ARTICLES.map(a=>a.slug)).size,INSIGHT_ARTICLES.length);
assert.equal(NEWS_ARCHIVE_DESKS.some(d=>d.slug==="beyond-the-deal"),false);
assert(NEWS_ARTICLES.every(a=>!articleMatchesVertical(VERTICALS.find(v=>v.slug==="beyond-the-deal")!,a)));
assert.equal(edition.heroImage.approval,"approved-editorial");
assert(edition.heroImage.width!>=3840 && edition.heroImage.height!>=2160);
assert(readFileSync("public"+edition.heroImage.src).length>0);
assert.equal(sitemap().some(e=>e.url.endsWith('/insights/'+edition.slug)),!edition.linkedinUrl);
assert(readFileSync("app/news/page.tsx","utf8").includes('initialParams.desk === "beyond-the-deal"'));
assert(readFileSync("app/v/[slug]/page.tsx","utf8").includes('permanentRedirect("https://www.investwithraj.com/newsletter")'));
console.log('PASS: newsletter registry, source master, news separation, legacy navigation, canonical sitemap');
